### ISSUE TITLE
errors due to dor-services gem v8 configuration changes

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/lyberservices-scripts#43]
**Describe the bug**

dor-services gem v8 validates configuration now, so unrecognized keys in consumer configuration cause errors:
- https://app.honeybadger.io/projects/64303/faults/60086009
- https://app.honeybadger.io/projects/64303/faults/60122548
- https://app.honeybadger.io/projects/64303/faults/60122525

**User Impact**

prevents scripts from being used.

**To Reproduce**

**Expected behavior**

scripts to run

**Screenshots**

**Additional context**

**Comment by peetucket** [comment]
these specific ones are all resolved by the shared_configs updates...i resolved all of the HB errors and will close this (and will open a new ticket if there are other errors that crop up in lyberservices-scripts)
