### ISSUE TITLE
pre_assemble script needs to interact cleanly with versioningWF

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/lyberservices-scripts#44]
**Describe the bug**

see sul-dlss/argo#1781

To run an object through the lyberservices-scripts, the user needs to manually open a version in Argo (?).   However, when lyberservices-scripts run `bundle.pre_assemble`, they kick off `assemblyWF` and `accessioningWF`, which can complete, but then the `versioningWF` needs to be manually set to completed in Argo.

**User Impact**

PITA for Andrew or anyone else who uses this code for object assembly and accessioning.

**Comment by andrewjbtw** [comment]
Confirmed that this works with a couple of reaccessions today.
