### ISSUE TITLE
permissions for "scripts" user are not recognized on the common-accessioning machines

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/lyberservices-scripts#45]
**Describe the bug**
When accessioning via the pre-assembly script as the scripts user, the folder and files created on the /dor/assembly druid tree are owned by the "scripts" user. This user id is not recognized on the common accessioning machines where user id and group id are just shown as "508".

This results in errors at various workflow steps because the robots do not have modify/create permissions in the druid tree.

**User Impact**
Accessioning halts with an error until permissions are changed. Generally, I've just been logging in as the scripts user and running  ```chmod -R 777``` as the least effort correction to make. I don't think I have the permission myself to change ownership with chown.

**To Reproduce**
1. Run preassembly from lyber-services scripts
2. Watch for a permissions related error in the assemblyWF. 
3. If you don't fix permissions at the folder level after the first error (i.e. if you only fix the specific file referenced in the error), you will likely also see a permissions error in the accessionWF.

**Expected behavior**
Permissions should be handled automatically.

**Additional context**
I believe this started when the scripts user was separated from the lyberadmin user. I think lyberadmin permissions are mapped to other machines, but I don't think that user has access to the current preassembly scripts at this point.

**Comment by jcoyne** [comment]
@rsmith11 Can you take a look at this?

**Comment by rsmith11** [comment]
It looks like the `scripts` user on sul-lyberservices-prod is set to UID 508.  That UID is not used on the preassembly and common-accessioning boxes, so that's where the permissions issue comes in.  Let me do some investigating and get back to this.

**Comment by ndushay** [comment]
I think this user needs to align as well:  server 'sul-preassembly-prod.stanford.edu', user: 'preassembly', 

(and for stage servers for all too, of course.)

**Comment by ndushay** [comment]
@tallenaz remembered that the scripts user was put into play because when this repo was split off from pre-assembly repo, they didn't want to mess up any shared_configs use on the lyberadmin user on the sul-lyberservices boxes.  

@rsmith11 believes the problem may be resolvable by changing the group of the scripts user to match the group id of the user(s) for pre-assemby and for common-accessioning.

I will double check that lyberadmin account on lyberservices boxes isn't using shared_configs for anything, in case Rob's approach doesn't work.

**Comment by ndushay** [comment]
I have 90% confidence that none of the below is current and none of it uses shared_configs.

```
[scripts@sul-lyberservices-prod lyberadmin]$ ll -rt /home/lyberadmin
total 392900
drwxrwxr-x 8 lyberadmin tomcat         4096 Apr 23  2012 apps
drwxrwxr-x 2 lyberadmin lyberteam      4096 Apr 26  2012 certs
drwxrwxr-x 2 lyberadmin lyberteam      4096 Apr 26  2012 tmpconfig
-rw-rw-r-- 1 lyberadmin lyberteam    669949 Apr 27  2012 puppet-agent-messages
drwxrwxr-x 4 lyberadmin lyberteam      4096 Apr 30  2012 share
drwxrwxr-x 7 lyberadmin lyberteam      4096 May  7  2012 remediator
drwxrwxr-x 5 lyberadmin lyberteam      4096 Oct 15  2012 media_md_gen
-rw-rw-r-- 1 lyberadmin lyberteam         0 Nov  1  2012 cron.log
-rw-rw-r-- 1 lyberadmin lyberteam         0 Nov  1  2012 check_robots.sh
-rw-rw-r-- 1 lyberadmin lyberteam   1233954 Nov 16  2012 republisher_output
drwxrwxr-x 3 lyberadmin lyberteam      4096 Nov 19  2012 oradiag_lyberadmin
-rw-rw-r-- 1 lyberadmin lyberteam         0 Aug 23  2013 copy_to_purl.log
drwxrwxr-x 2 lyberadmin lyberteam      4096 Nov 20  2013 tape-retrieval
drwxrwxr-x 3 lyberadmin lyberteam      4096 Jun 24  2014 scripts
drwxrwxr-x 2 lyberadmin lyberteam      4096 Feb 17  2015 bin
drwxrwxr-x 5 lyberadmin lyberteam      4096 Apr  7  2015 assembly
drwxr-xr-x 8 lyberadmin lyberteam      4096 May 26  2015 object-merge
-rw-rw-r-- 1 lyberadmin lyberteam 399804535 Mar 29  2016 yesterday.log
drwxrwxr-x 2 lyberadmin lyberteam      4096 Jul 22  2016 calavt
drwxrwxr-x 7 lyberadmin lyberteam      4096 Nov 16  2016 drh
drwxrwxr-x 4 lyberadmin lyberteam      4096 Nov 16  2016 cabeer
-rw-rw-r-- 1 lyberadmin lyberteam        93 Apr 17  2017 sgs_april2017_batches_1-2.out
-rw-rw-r-- 1 lyberadmin lyberteam        93 Apr 17  2017 rumsey_april2017_batches_1-2.out
drwxr-xr-x 4 lyberadmin lyberteam      4096 Aug 14  2017 wf-log-watcher
-rw-rw-r-- 1 lyberadmin lyberteam      7779 Oct 26  2017 backup_release_wfaj.tar.gz
-rw-rw-r-- 1 lyberadmin lyberteam     40960 Oct 26  2017 rolled-back-release-20171025213924.tar
drwxrwxr-x 3 lyberadmin lyberteam      4096 Oct 26  2017 home
-rw-rw-r-- 1 lyberadmin lyberteam     46516 Aug  1  2018 workspace_remediation_needed_druids
drwxrwxr-x 5 lyberadmin lyberteam      4096 Dec 18  2018 workflow-archiver-job
drwxrwxr-x 6 lyberadmin lyberteam      4096 May  8  2019 robot-master
drwxrwxr-x 5 lyberadmin lyberteam      4096 Aug 12 08:21 dor-utils-subsumed-by-argo
drwxrwxr-x 5 lyberadmin lyberteam      4096 Sep  9 05:16 pre-assembly-moved-to-lyberservices-scripts-dir
drwxrwxr-x 4 lyberadmin lyberteam      4096 Sep 13 11:07 tmp
drwxrwxr-x 2 lyberadmin lyberteam      4096 Sep 13 15:37 lmcrae
drwxrwxr-x 5 lyberadmin lyberteam      4096 Sep 23 04:25 lyberservices-scripts-moved-to-scripts-user
-rw-r--r-- 1 root       root            202 Oct 31 13:31 sulair-lyberservices
```

**Comment by rsmith11** [comment]
I've changed the gid of the scripts user on sul-lyberservices-test.  If it can be tested before I make the change on production, that would be great.

**Comment by ndushay** [comment]
@andrewjbtw will test this on stage with newly created files from the scripts user on using lyberservices-scripts repo from sul-lyberservices-test VM.

**Comment by andrewjbtw** [comment]
Just tested with a new session as the scripts user with newly created files. The gid is getting translated across machines but it looks like the default is to create folders as 755 and files as 644, so the group doesn't have write permissions for folders and files created by the scripts user:

This is what I see for this druid on stage: https://argo-stage.stanford.edu/view/druid:ct154ph6869

```[lyberadmin@common-accessioning-stage-a ~]$ cd /dor/assembly/ct/154/ph/6869/
[lyberadmin@common-accessioning-stage-a 6869]$ ls -l
total 4
drwxr-xr-x 4 506 lyberadmin 4096 Jan 30 19:02 ct154ph6869
[lyberadmin@common-accessioning-stage-a 6869]$ ls -lR
.:
total 4
drwxr-xr-x 4 506 lyberadmin 4096 Jan 30 19:02 ct154ph6869

./ct154ph6869:
total 8
drwxr-xr-x 2 506 lyberadmin 4096 Jan 30 19:02 content
drwxr-xr-x 2 506 lyberadmin 4096 Jan 30 19:02 metadata

./ct154ph6869/content:
total 0
-rw-r--r-- 1 506 lyberadmin 7 Jan 30 19:02 ct154ph6869.txt

./ct154ph6869/metadata:
total 4
-rw-r--r-- 1 506 lyberadmin 348 Jan 30 19:02 contentMetadata.xml
```

**Comment by rsmith11** [comment]
I've updated the scripts user .bashrc file to force a umask of 775 on files/folders.  Can you give it a try now when you get a chance?

**Comment by andrewjbtw** [comment]
I think this is likely fixed now, but unrelated changes on stage are preventing items from finishing accessioning at the moment. I'll confirm once I'm able to get an item all the way through the accessioning pipeline.

**Comment by andrewjbtw** [comment]
Confirming that this works now. I was able to accession and reaccession today with no problems.

**Comment by rsmith11** [comment]
Thanks.  I've submitted a puppet PR to make the changes on production lyberservices.
